[package]
name = "fini"
version = "1.4.0"
edition = "2024"
rust-version = "1.85"
description = "A fast, interactive CLI todo list tool"
repository = "https://github.com/sirbrillig/fini"
license = "MIT"
authors = ["Payton Swick <payton@foolord.com>"]

[dependencies]
arboard = "3.6.1"
chrono = { version = "0.4.42" }
clap = { version = "4.5.51", features = ["derive"] }
colored = "2.1.0"
config = { version = "0.15.19", default-features = false, features = ["toml", "json", "yaml"] }
directories = "6.0.0"
glob = "0.3"
inquire = { version = "0.9.1", features = ["editor", "date"] }
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
strip-ansi-escapes = "0.2.1"
tempfile = "3.23.0"
webbrowser = "1.0.6"
rustyline = { version = "15.0", features = ["derive"] }
terminal_size = "0.4.3"

[patch.crates-io]
inquire = { git = "https://github.com/sirbrillig/inquire", branch = "add-select-on-submit-to-multi-select", subdirectory = "inquire" }
