[package]
name = "fini"
version = "0.3.0"
edition = "2024"
license = "MIT"
authors = ["Payton Swick <payton@foolord.com>"]

[dependencies]
arboard = "3.6.1"
chrono = { version = "0.4.42" }
clap = { version = "4.5.51", features = ["derive"] }
colored = "2.1.0"
config = "0.15.19"
directories = "6.0.0"
edit = "0.1.5"
glob = "0.3"
inquire = { version = "0.9.1", features = ["editor", "date"] }
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
strip-ansi-escapes = "0.2.1"
tempfile = "3.23.0"
webbrowser = "1.0.6"
