[package]
name = "fini"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Payton Swick <payton@foolord.com>"]

[dependencies]
arboard = "3.6.1"
chrono = { version = "0.4.42", features = ["serde"] }
clap = { version = "4.5.51", features = ["derive"] }
colored = "2.1.0"
directories = "6.0.0"
edit = "0.1.5"
inquire = { version = "0.9.1", features = ["editor"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tempfile = "3.23.0"
